version: "2"
services:
  api_service_tools:
    build: .
    container_name: api_service_tools
    environment:
      - DB_USER=psql_user
      - DB_PASSWORD=psql_password
    links:
      - postgres:psql_host
  postgres:
    image: postgres:9.5
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=psql_user
      - POSTGRES_PASSWORD=psql_password
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
